### ISSUE TITLE
virtual machine image file

### ISSUE THREAD

**Issue by nuppt** [wly000/toutiao-project#1]
Hi, could you share the vm image files in project?

**Comment by wly000** [comment]
链接: https://pan.baidu.com/s/148Tj1qyTDm6Bfm8yaogMIw 提取码: gfxy 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by nuppt** [comment]
Thank you for your kind sharing ~

**Comment by nuppt** [comment]
How could I find the account and passwd of these VMs? Thanks!

![image](https://user-images.githubusercontent.com/8719521/75115359-97cc7c80-5698-11ea-96d0-b45c7e2cfae5.png)

**Comment by wly000** [comment]
itcast

**Comment by nuppt** [comment]
thanks a lot!

**Comment by nuppt** [comment]
Hi, dear friend.
I noticed that the database in VMs is `meiduo_mall`, not the expected dataset named `toutiao` which is the article recomendation business data.  
Is there a way to get the `toutiao` dataset for this project?

![image](https://user-images.githubusercontent.com/8719521/75180897-0df3e080-5778-11ea-9289-008941be19e8.png)
![image](https://user-images.githubusercontent.com/8719521/75180928-1f3ced00-5778-11ea-9ee5-ae2a64240a4d.png)

**Comment by wly000** [comment]
Database used in this  project is in Hive and HBase.

**Comment by nuppt** [comment]
It's weird that I cannot find out the database in neither Hive nor HBase. Is there any misunderstanding I'm falling into?

![image](https://user-images.githubusercontent.com/8719521/75212654-867f8f00-57c2-11ea-8ee6-1342b5dd7208.png)
![image](https://user-images.githubusercontent.com/8719521/75212841-17ef0100-57c3-11ea-9ef0-b96ba0e9876f.png)

**Comment by wly000** [comment]
The data for this project needs to be imported into Hive or HBase for subsequent analysis. So maybe there is no data in the official VM. The full  project and guidance are incuding in the link blow.

https://pan.baidu.com/s/1R2KYn4o8eRDzdn1dd8xKgw     k1o6

**Comment by nuppt** [comment]
Oh...I see!
And I have to say thanks again for your selfless sharing without reservation and detailed help for me ☺

**Comment by Nisoka** [comment]
> The data for this project needs to be imported into Hive or HBase for subsequent analysis. So maybe there is no data in the official VM. The full project and guidance are incuding in the link blow.
> 
> https://pan.baidu.com/s/1R2KYn4o8eRDzdn1dd8xKgw k1o6

你好，这个地址不能访问了，能不能帮忙再提供一个链接， 谢谢
